// <auto-generated />
using System;
using LiBookerWebApi.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace LiBookerWebApi.Migrations
{
    [DbContext(typeof(LiBookerDbContext))]
    partial class LiBookerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LiBookerWebApi.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("NUMBER(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("PersonId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("\"NormalizedUserName\" IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("LiBookerWebApi.Models.Entities.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_AUTORA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("MENO");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("NVARCHAR2(35)")
                        .HasColumnName("PRIEZVISKO");

                    b.Property<string>("Nationality")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NARODNOST");

                    b.HasKey("Id")
                        .HasName("PK_AUTOR");

                    b.ToTable("AUTOR", (string)null);
                });

            modelBuilder.Entity("LiBookerWebApi.Models.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_KNIHY");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("CLOB")
                        .HasColumnName("POPIS");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("NAZOV");

                    b.HasKey("Id")
                        .HasName("PK_KNIHA");

                    b.ToTable("KNIHA", (string)null);
                });

            modelBuilder.Entity("LiBookerWebApi.Models.Entities.BookAuthor", b =>
                {
                    b.Property<int>("AuthorId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_AUTORA");

                    b.Property<int>("BookId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_KNIHY");

                    b.HasKey("AuthorId", "BookId")
                        .HasName("PK_KNIHY");

                    b.HasIndex("BookId");

                    b.ToTable("KNIHY", (string)null);
                });

            modelBuilder.Entity("LiBookerWebApi.Models.Entities.BookCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_KATEGORIE");

                    b.Property<int>("BookId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_KNIHY");

                    b.HasKey("CategoryId", "BookId")
                        .HasName("PK_KATEGORIE_KNIH");

                    b.HasIndex("BookId");

                    b.ToTable("KATEGORIE_KNIH", (string)null);
                });

            modelBuilder.Entity("LiBookerWebApi.Models.Entities.BookGenre", b =>
                {
                    b.Property<int>("GenreId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ZANRA");

                    b.Property<int>("BookId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_KNIHY");

                    b.HasKey("GenreId", "BookId")
                        .HasName("PK_ZANRE_KNIH");

                    b.HasIndex("BookId");

                    b.ToTable("ZANRE_KNIH", (string)null);
                });

            modelBuilder.Entity("LiBookerWebApi.Models.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_KATEGORIE");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("NAZOV");

                    b.HasKey("Id")
                        .HasName("PK_KATEGORIA");

                    b.ToTable("KATEGORIA", (string)null);
                });

            modelBuilder.Entity("LiBookerWebApi.Models.Entities.Copy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_VYTLACKA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PublicationId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_VYDANIA");

                    b.Property<string>("Status")
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("STAV");

                    b.HasKey("Id")
                        .HasName("PK_VYTLACOK");

                    b.HasIndex("PublicationId");

                    b.ToTable("VYTLACOK", (string)null);
                });

            modelBuilder.Entity("LiBookerWebApi.Models.Entities.CoverImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_OBRAZKU");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("OBRAZOK");

                    b.HasKey("Id")
                        .HasName("PK_TITULNY_OBRAZOK");

                    b.ToTable("TITULNY_OBRAZOK", (string)null);
                });

            modelBuilder.Entity("LiBookerWebApi.Models.Entities.Fine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_POKUTY");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("NUMBER")
                        .HasColumnName("CENA");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DAT_ZAPLATENIA");

                    b.HasKey("Id")
                        .HasName("PK_POKUTA");

                    b.ToTable("POKUTA", (string)null);
                });

            modelBuilder.Entity("LiBookerWebApi.Models.Entities.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ZANRA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("NAZOV");

                    b.HasKey("Id")
                        .HasName("PK_ZANER");

                    b.ToTable("ZANER", (string)null);
                });

            modelBuilder.Entity("LiBookerWebApi.Models.Entities.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_JAZYKA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("NVARCHAR2(3)")
                        .HasColumnName("SKRATKA");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("NAZOV");

                    b.HasKey("Id")
                        .HasName("PK_JAZYK");

                    b.ToTable("JAZYK", (string)null);
                });

            modelBuilder.Entity("LiBookerWebApi.Models.Entities.Loan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_VYPOZICANIA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CopyId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("VYTLACOK_ID_VYTLACKA");

                    b.Property<DateTime>("DueAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DAT_KONCA_VYPOZ");

                    b.Property<int?>("FineId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("O_POKUTA");

                    b.Property<DateTime>("LoanedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DAT_VYPOZICANIA");

                    b.Property<int>("PersonId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("OSOBA_ID_OSOBY");

                    b.Property<DateTime?>("ReturnedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DAT_VRATENIA");

                    b.HasKey("Id")
                        .HasName("PK_VYPOZICANIE");

                    b.HasIndex("CopyId");

                    b.HasIndex("FineId");

                    b.HasIndex("PersonId");

                    b.ToTable("VYPOZICANIE", (string)null);
                });

            modelBuilder.Entity("LiBookerWebApi.Models.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_OSOBY");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DAT_NARODENIA");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("MENO");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("POHLAVIE");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("NVARCHAR2(35)")
                        .HasColumnName("PRIEZVISKO");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("TEL_CISLO");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DAT_REGISTRACIE");

                    b.HasKey("Id")
                        .HasName("PK_OSOBA");

                    b.ToTable("OSOBA", (string)null);
                });

            modelBuilder.Entity("LiBookerWebApi.Models.Entities.Publication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_VYDANIA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_KNIHY");

                    b.Property<int>("CoverImageId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_OBRAZKU");

                    b.Property<int>("EditionNumber")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CISLO_VYDANIA");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("NVARCHAR2(17)")
                        .HasColumnName("ISBN");

                    b.Property<int>("LanguageId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_JAZYKA");

                    b.Property<int>("PageCount")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("POCET_STRAN");

                    b.Property<int>("PublisherId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_VYDAVATELSTVA");

                    b.Property<string>("XmlProperties")
                        .HasColumnType("XMLTYPE")
                        .HasColumnName("VLASTNOSTI_XML");

                    b.Property<int>("Year")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ROK_VYDANIA");

                    b.HasKey("Id")
                        .HasName("PK_VYDANIE");

                    b.HasIndex("BookId");

                    b.HasIndex("CoverImageId");

                    b.HasIndex("LanguageId");

                    b.HasIndex("PublisherId");

                    b.ToTable("VYDANIE", (string)null);
                });

            modelBuilder.Entity("LiBookerWebApi.Models.Entities.Publisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_VYDAVATELSTVA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("CLOB")
                        .HasColumnName("POPIS");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("NAZOV");

                    b.HasKey("Id")
                        .HasName("PK_VYDAVATELSTVO");

                    b.ToTable("VYDAVATELSTVO", (string)null);
                });

            modelBuilder.Entity("LiBookerWebApi.Models.Entities.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_REZERVACIE");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PersonId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("OSOBA_ID_OSOBY");

                    b.Property<int>("PublicationId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("VYDANIE_ID_VYDANIA");

                    b.Property<DateTime>("ReservedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DAT_REZERVACIE");

                    b.HasKey("Id")
                        .HasName("PK_REZERVACIA");

                    b.HasIndex("PersonId");

                    b.HasIndex("PublicationId");

                    b.ToTable("REZERVACIA", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("\"NormalizedName\" IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("NVARCHAR2(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("Name")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("Value")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("LiBookerWebApi.Models.Entities.BookAuthor", b =>
                {
                    b.HasOne("LiBookerWebApi.Models.Entities.Author", "Author")
                        .WithMany("BookAuthors")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LiBookerWebApi.Models.Entities.Book", "Book")
                        .WithMany("BookAuthors")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("LiBookerWebApi.Models.Entities.BookCategory", b =>
                {
                    b.HasOne("LiBookerWebApi.Models.Entities.Book", "Book")
                        .WithMany("BookCategories")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LiBookerWebApi.Models.Entities.Category", "Category")
                        .WithMany("BookCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("LiBookerWebApi.Models.Entities.BookGenre", b =>
                {
                    b.HasOne("LiBookerWebApi.Models.Entities.Book", "Book")
                        .WithMany("BookGenres")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LiBookerWebApi.Models.Entities.Genre", "Genre")
                        .WithMany("BookGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("LiBookerWebApi.Models.Entities.Copy", b =>
                {
                    b.HasOne("LiBookerWebApi.Models.Entities.Publication", "Publication")
                        .WithMany("Copies")
                        .HasForeignKey("PublicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publication");
                });

            modelBuilder.Entity("LiBookerWebApi.Models.Entities.Loan", b =>
                {
                    b.HasOne("LiBookerWebApi.Models.Entities.Copy", "Copy")
                        .WithMany("Loans")
                        .HasForeignKey("CopyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LiBookerWebApi.Models.Entities.Fine", "Fine")
                        .WithMany("Loans")
                        .HasForeignKey("FineId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LiBookerWebApi.Models.Entities.Person", "Person")
                        .WithMany("Loans")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Copy");

                    b.Navigation("Fine");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("LiBookerWebApi.Models.Entities.Publication", b =>
                {
                    b.HasOne("LiBookerWebApi.Models.Entities.Book", "Book")
                        .WithMany("Publications")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LiBookerWebApi.Models.Entities.CoverImage", "CoverImage")
                        .WithMany("Publications")
                        .HasForeignKey("CoverImageId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("LiBookerWebApi.Models.Entities.Language", "Language")
                        .WithMany("Publications")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("LiBookerWebApi.Models.Entities.Publisher", "Publisher")
                        .WithMany("Publications")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("CoverImage");

                    b.Navigation("Language");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("LiBookerWebApi.Models.Entities.Reservation", b =>
                {
                    b.HasOne("LiBookerWebApi.Models.Entities.Person", "Person")
                        .WithMany("Reservations")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LiBookerWebApi.Models.Entities.Publication", "Publication")
                        .WithMany("Reservations")
                        .HasForeignKey("PublicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Publication");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("LiBookerWebApi.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("LiBookerWebApi.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LiBookerWebApi.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("LiBookerWebApi.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LiBookerWebApi.Models.Entities.Author", b =>
                {
                    b.Navigation("BookAuthors");
                });

            modelBuilder.Entity("LiBookerWebApi.Models.Entities.Book", b =>
                {
                    b.Navigation("BookAuthors");

                    b.Navigation("BookCategories");

                    b.Navigation("BookGenres");

                    b.Navigation("Publications");
                });

            modelBuilder.Entity("LiBookerWebApi.Models.Entities.Category", b =>
                {
                    b.Navigation("BookCategories");
                });

            modelBuilder.Entity("LiBookerWebApi.Models.Entities.Copy", b =>
                {
                    b.Navigation("Loans");
                });

            modelBuilder.Entity("LiBookerWebApi.Models.Entities.CoverImage", b =>
                {
                    b.Navigation("Publications");
                });

            modelBuilder.Entity("LiBookerWebApi.Models.Entities.Fine", b =>
                {
                    b.Navigation("Loans");
                });

            modelBuilder.Entity("LiBookerWebApi.Models.Entities.Genre", b =>
                {
                    b.Navigation("BookGenres");
                });

            modelBuilder.Entity("LiBookerWebApi.Models.Entities.Language", b =>
                {
                    b.Navigation("Publications");
                });

            modelBuilder.Entity("LiBookerWebApi.Models.Entities.Person", b =>
                {
                    b.Navigation("Loans");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("LiBookerWebApi.Models.Entities.Publication", b =>
                {
                    b.Navigation("Copies");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("LiBookerWebApi.Models.Entities.Publisher", b =>
                {
                    b.Navigation("Publications");
                });
#pragma warning restore 612, 618
        }
    }
}
